// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package main

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bus struct {
	ID        int32
	BusNumber pgtype.Text
}

type BusRoute struct {
	ID        int32
	RouteCode pgtype.Text
}

type Telemetry struct {
	ID                        int32
	TripID                    int32
	Time                      pgtype.Timestamp
	ElectricPowerDemand       pgtype.Numeric
	TemperatureAmbient        pgtype.Numeric
	TractionBrakePressure     pgtype.Numeric
	TractionTractionForce     pgtype.Numeric
	GnssAltitude              pgtype.Numeric
	GnssCourse                pgtype.Numeric
	GnssLatitude              pgtype.Numeric
	GnssLongitude             pgtype.Numeric
	ItcsBusRoute              pgtype.Text
	ItcsNumberOfPassengers    pgtype.Numeric
	ItcsStopName              pgtype.Text
	OdometryArticulationAngle pgtype.Numeric
	OdometrySteeringAngle     pgtype.Numeric
	OdometryVehicleSpeed      pgtype.Numeric
	OdometryWheelSpeedFl      pgtype.Numeric
	OdometryWheelSpeedFr      pgtype.Numeric
	OdometryWheelSpeedMl      pgtype.Numeric
	OdometryWheelSpeedMr      pgtype.Numeric
	OdometryWheelSpeedRl      pgtype.Numeric
	OdometryWheelSpeedRr      pgtype.Numeric
	StatusDoorIsOpen          pgtype.Bool
	StatusGridIsAvailable     pgtype.Bool
	StatusHaltBrakeIsActive   pgtype.Bool
	StatusParkBrakeIsActive   pgtype.Bool
}

type Trip struct {
	ID                   int32
	Name                 string
	BusID                pgtype.Int4
	RouteID              pgtype.Int4
	StartTime            pgtype.Timestamp
	EndTime              pgtype.Timestamp
	DrivenDistanceKm     pgtype.Numeric
	EnergyConsumptionKwh pgtype.Numeric
	ItcsPassengersMean   pgtype.Numeric
	ItcsPassengersMin    pgtype.Int4
	ItcsPassengersMax    pgtype.Int4
	GridAvailableMean    pgtype.Numeric
	TemperatureMean      pgtype.Numeric
	TemperatureMin       pgtype.Numeric
	TemperatureMax       pgtype.Numeric
}
