// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package main

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bus struct {
	ID        int32
	BusNumber pgtype.Text
}

type BusRoute struct {
	ID        int32
	RouteCode pgtype.Text
}

type Telemetry struct {
	ID                        int64
	TripID                    int32
	Time                      pgtype.Timestamp
	ElectricPowerDemand       pgtype.Float4
	TemperatureAmbient        pgtype.Float4
	TractionBrakePressure     pgtype.Float4
	TractionTractionForce     pgtype.Float4
	GnssAltitude              pgtype.Float4
	GnssCourse                pgtype.Float4
	GnssLatitude              pgtype.Float4
	GnssLongitude             pgtype.Float4
	ItcsBusRouteID            pgtype.Int4
	ItcsNumberOfPassengers    pgtype.Int4
	ItcsStopName              pgtype.Text
	OdometryArticulationAngle pgtype.Float4
	OdometrySteeringAngle     pgtype.Float4
	OdometryVehicleSpeed      pgtype.Float4
	OdometryWheelSpeedFl      pgtype.Float4
	OdometryWheelSpeedFr      pgtype.Float4
	OdometryWheelSpeedMl      pgtype.Float4
	OdometryWheelSpeedMr      pgtype.Float4
	OdometryWheelSpeedRl      pgtype.Float4
	OdometryWheelSpeedRr      pgtype.Float4
	StatusDoorIsOpen          pgtype.Bool
	StatusGridIsAvailable     pgtype.Bool
	StatusHaltBrakeIsActive   pgtype.Bool
	StatusParkBrakeIsActive   pgtype.Bool
}

type Trip struct {
	ID                   int32
	Name                 string
	BusID                pgtype.Int4
	RouteID              pgtype.Int4
	StartTime            pgtype.Timestamp
	EndTime              pgtype.Timestamp
	DrivenDistanceKm     pgtype.Float4
	EnergyConsumptionKwh pgtype.Int4
	ItcsPassengersMean   pgtype.Float4
	ItcsPassengersMin    pgtype.Int4
	ItcsPassengersMax    pgtype.Int4
	GridAvailableMean    pgtype.Float4
	AmbTemperatureMean   pgtype.Float4
	AmbTemperatureMin    pgtype.Float4
	AmbTemperatureMax    pgtype.Float4
}
