// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package main

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bus struct {
	ID        int32
	BusNumber pgtype.Text
}

type BusRoute struct {
	ID        int32
	RouteCode pgtype.Text
}

type Trip struct {
	ID                   int32
	Name                 string
	BusID                pgtype.Int4
	RouteID              pgtype.Int4
	StartTime            pgtype.Timestamp
	EndTime              pgtype.Timestamp
	DrivenDistanceKm     pgtype.Float4
	EnergyConsumptionKwh pgtype.Float4
	ItcsPassengersMean   pgtype.Float4
	ItcsPassengersMin    pgtype.Int4
	ItcsPassengersMax    pgtype.Int4
	GridAvailableMean    pgtype.Float4
	TemperatureMean      pgtype.Float4
	TemperatureMin       pgtype.Float4
	TemperatureMax       pgtype.Float4
}
